name: Setup
description: Setup project with pnpm

outputs:
  cache-hit:
    description: 'Whether restoring the cache was successful or not'
    value: ${{ steps.setup-node.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Setup tools
      uses: jdx/mise-action@v2.4.4

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
