name: Setup
description: Setup project with mise

outputs:
  cache-hit:
    description: 'Whether restoring the cache was successful or not'
    value: ${{ steps.mise-install.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Install tools
      id: mise-install
      uses: jdx/mise-action@v2

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
