name: Commit and Sync
description: Commit changes and push back to repository

inputs:
  message:
    description: Commit message
    default: ''
  user:
    description: Git user name
    default: github-actions[bot]
  email:
    description: Git user email
    default: github-actions[bot]@users.noreply.github.com
  amend:
    description: Whether to ammend the last commit
    default: 'false'

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "${{ inputs.user }}"
        git config user.email "${{ inputs.email }}"

    - name: Check in all changes
      shell: bash
      run: git add -A

    - name: Commit and push (new commit)
      shell: bash
      if: inputs.amend == 'false'
      run: |
        git commit -m '${{ inputs.message }}'
        git push

    - name: Commit and push (amend commit)
      shell: bash
      if: inputs.amend == 'true'
      run: |
        git commit --amend --no-edit
        git push --force
