name: CI

on:
  workflow_call:
  pull_request:
    branches: [main, beta]

jobs:
  checks:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        type: ['test', 'lint', 'build']
    name: Run ${{ matrix.type }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install tools with mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Install dependencies
        run: pnpm ci

      - run: mise r ${{ matrix.type }}
