name: CI

on:
  push:
    branches: [renovate/**]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # ========== SETUP ========== #
      - name: Check out repository
        uses: actions/checkout@v4.1.6

      # Setup node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      # Get metadata
      - name: Get pnpm store directory
        id: get-pnpm-store
        shell: bash
        run: echo "path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      # Setup the cache
      - uses: actions/cache@v4
        name: Restore cache
        id: cache-deps
        with:
          path: ${{ steps.get-pnpm-store.outputs.path }}
          key:
            deps_os-${{ runner.os }}_arch-${{ runner.arch }}_${{
            hashFiles('./pnpm-lock.yaml') }}

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        shell: bash

      # ========== CHECK ========== #
      - name: Run checks
        run: pnpm test
        shell: bash
