name: CI

on:
  workflow_call:
  pull_request:
    branches: [main, beta]

jobs:
  checks:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        type: ['test', 'lint', 'build']
    name: Run ${{ matrix.type }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install tools with mise
        uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5

      - name: Install dependencies
        run: pnpm ci

      - run: mise r ${{ matrix.type }}
